

export const homeObjectOne = {
    id: 'desprenoi',
    lightBg:true,
    lightText:false,
    lightTextSubtitle:false,
    topLine:'Despre Noi',
    heading:`Servicii complete in domeniul enerigiei electrice si automatizarilor`,
    subtitle:'Energia electrică a schimbat modul în care trăiesc oamenii. Inventatorul Thomas Edison a dat startul in acest domeniu, iar noi ne-am propus sa nu lasam acest lucru la întâmplare.Asadar, Edisson-Industries este firmă autorizată A.N.R.E. care face ca instalațiile electrice să vă ofere siguranță deplină.',
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart:false,
    img:require ('../../../assets/electric-6.jpg'),
    alt:'image alt description',
    showButton: true,
    buttonTo: 'despre-noi',
    buttonText: 'Citeste mai mult'
};

export const homeObjectTwo = {
    id: 'servicii',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Servicii prestate',
    heading: 'Pentru orice problema, noi avem solutia ',
    subtitle: "Indiferent daca proiectul este unul simplu sau de anvergura, va punem la dispozitie toate cunostintele noastre, astfel incat totul sa iasa perfect. Planificam, proiectam, construim, imbunatatim, extindem, modernizam, optimizam infrastructura și facilitatile, astfel incat sa transformam proiectul din concept in realitate.",
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-7.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: 'Servicii',
    buttonText: 'Citeste mai mult'
};
export const homeObjectThree = {
    id: 'mai mult despre noi',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Edisson-Industries',
    heading: 'Privire de ansamblu ',
    subtitle: "De-a lungul anilor, energia electrică a schimbat modul în care trăiesc oamenii. O utilizăm zilnic în toate zonele vieții noastre: încărcare gadgeturi, curățare haine, pentru a găti, a ne menține cald sau răcoare și multe altele.\nÎncă de la înființarea firmei, am fost hotărâți să nu lăsăm lucrurile la întâmplare.Edisson Industries este o firmă autorizată ANRE.Scopul nostru e ca instalații electrice să vă ofere siguranță deplină, atât în locuințe, cât și în mediul de lucru.\nSunt multe persoane care au învățat de la alții cum să fixeze o priză în perete și să schimbe un întrerupător, dar sunt puțini cei care știu ceea ce fac. Este important să înțelegem că astfel de lucrări/intervenții electrice trebuie realizate doar de către persoane autorizate.\nNu uitați că improvizațiile sau reparațiile efectuate de către persoane necalificate vă pot pune viața în pericol!\nFie că e vorba de branșamente, automatizări sau de o simplă verificare a instalației electrice, Edisson Industries este firma pe care ar trebui să o contactezi.\nSuntem mereu echipați pentru a veni în ajutorul tău cât mai rapid.",
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    img: require('../../../assets/electric-8_resize.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: 'contact',
    buttonText:'Contacteaza-ne'
};

export const despreNoiContentObject = {
    id: 'despre-noi Page',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Despre noi',
    heading: `Edisson-Industries: Companie instalatii electrice`,
    subtitle: `Indiferent daca proiectul este unul simplu sau de anvergura, va punem la dispozitie toate cunostintele noastre, astfel incat totul sa iasa perfect.\nPlanificam, proiectam, construim, upgradam, extindem, modernizam, optimizam infrastructura și facilitatile, astfel incat sa transformam proiectul din concept in realitate.De-a lungul anilor, energia electrică a schimbat modul în care trăiesc oamenii. O utilizăm zilnic în toate zonele vieții noastre: încărcare gadgeturi, curățare haine, pentru a găti, a ne menține cald sau răcoare și multe altele.\nÎncă de la înființarea firmei, am fost hotărâți să nu lăsăm lucrurile la întâmplare.Edisson Industries este o firmă autorizată ANRE.Scopul nostru e ca instalații electrice să vă ofere siguranță deplină, atât în locuințe, cât și în mediul de lucru.\nSunt multe persoane care au învățat de la alții cum să fixeze o priză în perete și să schimbe un întrerupător, dar sunt puțini cei care știu ceea ce fac. Este important să înțelegem că astfel de lucrări/intervenții electrice trebuie realizate doar de către persoane autorizate.u uitați că improvizațiile sau reparațiile efectuate de către persoane necalificate vă pot pune viața în pericol!\nFie că e vorba de branșamente, automatizări sau de o simplă verificare a instalației electrice, Edisson Industries este firma pe care ar trebui să o contactezi.\nSuntem mereu echipați pentru a veni în ajutorul tău cât mai rapid.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-14.jpg'),
    alt: 'image alt description',
    showButton: false,
    buttonTo: '',
};
export const serviciiContentObject1 = {
    id: 'servicii Page informatii generale',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Servicii prestate',
    heading: `Pentru orice problema, noi avem solutia`,
    subtitle: `Indiferent daca proiectul este unul simplu sau de anvergura, va punem la dispozitie \ntoate cunostintele noastre, astfel incat totul sa iasa perfect.\nPlanificam, proiectam, construim, upgradam, extindem, modernizam, optimizam infrastructura și facilitatile, \nastfel incat sa \ntransformam proiectul\ndin concept in realitate.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-3.jpg'),
    alt: 'image alt description',
    showButton: false,
    buttonTo: ""
};
export const serviciiContentObject2 = {
    id: 'servicii Page Proiectare instalatii electrice',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Servicii',
    heading: `Proiectare instalatii electrice`,
    subtitle: `Echipa Edisson-Industries va ofera cele mai bune servicii de proiectare a instalatiilor electrice pentru imobile de locuinte, locuinte unifamiliare, hale industriale, cladiri de birouri, etc.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    img: require('../../../assets/electric-9.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-proiectare-instalatii-electrice',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject3 = {
    id: 'servicii Page Executare instalatii electrice',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Servicii',
    heading: `Executare instalatii electrice`,
    subtitle: `Echipa firmei noastre este formata din electricieni profesionisti autorizati ANRE. Acestia pot efectua toate lucrarile de executie pentru instalatii electrice, respectand normele de siguranta.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-2.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-executare-instalatii-electrice',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject4 = {
    id: 'servicii Page Bransamente instalatii electrice',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Servicii',
    heading: `Bransamente instalatii electrice`,
    subtitle: `Edisson-Industries are capabilitatea de a va ajuta cu privire la racordarea la reteaua de distributie a energiei electrice. `,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    img: require('../../../assets/electric-15.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-bransamente-instalatii-electrice',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject5 = {
    id: 'servicii Page Automatizari KNX',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Servicii',
    heading: `Automatizari KNX`,
    subtitle: `Pe langa celelalte servicii, compania noastra ofera servicii in domeniul automatizarilor inteligente - sisteme KNX. KNX poate fi folosit pentru toate functiile necesare controlului caselor si cladirilor.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-19.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-automatizari-knx',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject6 = {
    id: 'servicii Page Executie si masuratori PRAM',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Servicii',
    heading: `Executie si masuratori PRAM`,
    subtitle: `Edisson-Industries presteaza servicii de verificari si masuratori PRAM pentru prize de pamant si sisteme paratrasnet, avand in echipa persoane calificare si competente pentru astfel de servicii.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    img: require('../../../assets/electric-1.jpg'),
    alt: 'Imagine serviciul de Executie si masuratori PRAM',
    showButton: true,
    buttonTo: "/servicii-executie-si-masuratori-PRAM",
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject7 = {
    id: 'servicii Page Sisteme de supraveghere si antiefractie',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Servicii',
    heading: `Sisteme de supraveghere si antiefractie`,
    subtitle: `Oferim servicii de proiectare si executie a sistemelor de supraveghere video si antiefractie. Scopul este acela de a oferi siguranta 100%.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-20.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '"/servicii-sisteme-supraveghere-si-antiefractie',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject8 = {
    id: 'servicii Page Mententata si revizii la echipamente si instalatii electrice',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Servicii',
    heading: `Mententata si revizii la echipamente si instalatii electrice`,
    subtitle: `Avand in vedere reglementarile in vigoare, periodic este necesar ca fiecare instalatie electrica sa fie revizuita. Echipa noastra vine in ajutorul clientilor cu servicii de mentenata si revizii atat a echipamentelor, cat si a instalatiilor electrice.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    img: require('../../../assets/electric-16.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-mentenanta-si-revizii-instalatii-electrice',
    buttonText: 'Vezi detalii'
};
export const serviciiContentObject9 = {
    id: 'servicii Page Sisteme fotovoltaice',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Servicii',
    heading: `Sisteme fotovoltaice`,
    subtitle: `Energia solară fotovoltaică este energie produsă prin celule fotovoltaice solare, care convertesc lumina soarelui direct în energie electrică.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-21.jpg'),
    alt: 'image alt description',
    showButton: true,
    buttonTo: '/servicii-sisteme-fotovoltaice',
    buttonText: 'Vezi detalii'
};

export const contactContentObject = {
    id: 'contact Page',
    lightBg: true,
    lightText: false,
    lightTextSubtitle: false,
    topLine: 'Contacteaza Edisson-Industries',
    heading: `Contacteaza-ne pentru orice problema`,
    subtitle: `Intra in legatura cu echipa noastra pentru a discuta detalii despre proiectul tau.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: true,
    img: require('../../../assets/electric-13.jpg'),
    alt: 'image alt description',
    showButton: false,
    buttonTo: '',
};
export const contactContentWithMap = {
    id: 'contact Page Map and Form section',
    lightBg: false,
    lightText: true,
    lightTextSubtitle: true,
    topLine: 'Contacteaza Edisson-Industries',
    heading: `Completeaza formularul de mai jos`,
    subtitle: `Intra in legatura cu echipa noastra pentru a discuta detalii despre proiectul tau.`,
    showSubtitleList: false,
    subtitleHeader: '',
    imgStart: false,
    showButton: false,
    buttonTo: '',
};